# NumPy Tutorial

## NumPy Basics

In [2]:
#importing Numpy Library
import numpy as np

In [3]:
# Creating arrays
array1 = np.array([1, 2, 3])
array1

array([1, 2, 3])

In [4]:
#creating array with in a range (start,stop,step)
array2 = np.arange(0, 10, 2)
array2

array([0, 2, 4, 6, 8])

In [5]:
#return evenly spaced numbers over a specified interval
array3 = np.linspace(0, 1, 5)
array3

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [6]:
#return a new array of given shape and type, filled with zeros
array4 = np.zeros((3, 3))
array4

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
#return a new array of given shape and type, filled with zeros
array5 = np.ones((3, 3))
array5

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
#return a new array of given shape and type, filled with given values
array6 = np.full((2, 3), 7)
array6

array([[7, 7, 7],
       [7, 7, 7]])

In [14]:
#return with datatypes
array7 = np.array([1, 2, 3], dtype='float64')
print(array7)
array8 = array7.astype('int32')
print(array8)

[1. 2. 3.]
[1 2 3]


## Array Operations

In [15]:
#return the sum of two array which has same size
array_sum = np.add(array1, array2[:3])
array_sum

array([1, 4, 7])

In [16]:
#return the difference of two array which has same size
array_diff = np.subtract(array1, array2[:3])
array_diff

array([ 1,  0, -1])

In [17]:
#return the product of two array which has same size
array_prod = np.multiply(array1, array2[:3])
array_prod

array([ 0,  4, 12])

In [18]:
#made division of two array which has same size
array_div = np.divide(array2[:3],array1)
array_div

array([0.        , 1.        , 1.33333333])

In [19]:
#return the square root of array/value
array_sqrt = np.sqrt(array1)
print(array_sqrt)
sqrt=np.sqrt(9)
print(sqrt)

[1.         1.41421356 1.73205081]
3.0


In [20]:
#Calculate the exponential of all elements in the input array
array_exp = np.exp(array1)
array_exp

array([ 2.71828183,  7.3890561 , 20.08553692])

In [21]:
#Calculate Natural logarithm, element-wise
array_log = np.log(array1)
array_log

array([0.        , 0.69314718, 1.09861229])

## Indexing and Slicing

In [22]:
#return element from 1d array based on index
single_element = array1[0]
print(single_element)

#return element from multi dimensional array
multi_dim_element = array4[1, 2]
print(multi_dim_element)

#slicing the array
slice_array = array2[1:4]
print(slice_array)

#select elements from an array using a boolean condition
boolean_indexing = array1[array1 > 1 ]
print(boolean_indexing)

#access multiple elements of an array at once using an array of indices
fancy_indexing = array1[[0, 2]]
print(fancy_indexing)

1
0.0
[2 4 6]
[2 3]
[1 3]


## Array Shape Manipulation

In [23]:
# Reshaping array2 into a 2x3 array
reshaped_array = array2.reshape((5, 1))
print(reshaped_array)

# Flattening array2 into a 1D array
flattened_array = array2.ravel()
print(flattened_array)

# Concatenating array1 and the first three elements of array2
concatenated_array = np.concatenate((array1, array2[:3]))
print(concatenated_array)

# Stacking array1 and the first three elements of array2 vertically
vstacked_array = np.vstack((array1, array2[:3]))
print(vstacked_array)

# Stacking array1 and the first three elements of array2 horizontally
hstacked_array = np.hstack((array1, array2[:3]))
print(hstacked_array)

# Splitting array2 into 2 sub-arrays which allow unequal division
split_array = np.array_split(array2, 2)
print(split_array)

[[0]
 [2]
 [4]
 [6]
 [8]]
[0 2 4 6 8]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1 2 3 0 2 4]
[[1 2 3]
 [0 2 4]]
[1 2 3 0 2 4]
[array([0, 2, 4]), array([6, 8])]


## Mathematical Functions

In [35]:
# Sum of all elements in array1
array_sum = np.sum(array1)
print(array_sum)

#Raises each element in an array to a specified power.
power = 3
powered_values = np.power(array1, power)
print(powered_values)

# Mean of all elements in array1
array_mean = np.mean(array1)
print(array_mean)

# Standard deviation of all elements in array1
array_std = np.std(array1)
print(array_std)

# Variance of all elements in array1
array_var = np.var(array1)
print(array_var)

# Minimum value in array1
array_min = np.min(array1)
print(array_min)

# Maximum value in array1
array_max = np.max(array1)
print(array_max)

#Computes the absolute value of each element in an array.
array_a = np.array([-2, 3, -4, 5])
absolute_values = np.abs(array_a)
print(absolute_values)

#Rounds each element in an array to the nearest integer
array_f = np.array([1.1, 2.9, 3.5, 4.8])
rounded_values = np.round(array_f)
print(rounded_values)

#Rounds each element in an array to the nearest integer greater than or equal to it.
ceil_values = np.ceil(array_f)
print(ceil_values)

#Rounds each element in an array to the nearest integer less than or equal to it.
floor_values = np.floor(array_f)
print(floor_values)

# Cumulative sum of the elements in array1
cumulative_sum = np.cumsum(array1)
print(cumulative_sum)

# Cumulative product of the elements in array1
cumulative_prod = np.cumprod(array1)
print(cumulative_prod)

6
[ 1  8 27]
2.0
0.816496580927726
0.6666666666666666
1
3
[2 3 4 5]
[1. 3. 4. 5.]
[2. 3. 4. 5.]
[1. 2. 3. 4.]
[1 3 6]
[1 2 6]


## Linear Algebra

In [25]:
#Modifying array4
array4[0, 0] = 1
array4[1, 1] = 2
array4[2, 2] = 3
array4

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

In [32]:

# Dot product of array1 and the first three elements of array2
dot_product = np.dot(array1, array2[:3])
print(dot_product)

# Matrix product of the first 3x3 sub-array of array4 with itself
matrix_product = np.matmul(array4, array4)
print(matrix_product)

# Inverse of the first 3x3 sub-array of array4
inverse_matrix = np.linalg.inv(array4)
print(inverse_matrix)

# Determinant of the first 3x3 sub-array of array4
determinant = np.linalg.det(array4)
print(determinant)

# Eigenvalues and eigenvectors of the first 3x3 sub-array of array4
eigenvalues, eigenvectors = np.linalg.eig(array4)
print(eigenvalues)
print(eigenvectors)

# Transposing the array (flipping rows and columns)
array_t=np.array([[1,2,3],[4,5,6],[7,8,9]])
transposed_array = array_t.T
print(transposed_array)
#or
transposed_array1=np.transpose(array_t)
print(transposed_array1)

# Create a 4x4 identity matrix
identity_matrix = np.identity(4)
print(identity_matrix)

16
[[1. 0. 0.]
 [0. 4. 0.]
 [0. 0. 9.]]
[[1.         0.         0.        ]
 [0.         0.5        0.        ]
 [0.         0.         0.33333333]]
6.0
[1. 2. 3.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Random Number Generation

In [144]:
# Generate a 3x3 array of random floats between 0 and 1
random_array = np.random.rand(3, 3)
print(random_array)

# Generate a 3x3 array of random integers between 0 and 10
random_int_array = np.random.randint(0, 10, (3, 3))
print(random_int_array)

# Randomly choose 3 elements from array1
array1 = np.array([1, 2, 3])
random_choice = np.random.choice(array1, size=3)
print(random_choice)

# Shuffle array2 in place
array2 = np.arange(0, 10, 2)
np.random.shuffle(array2)
print(array2)

# Set the random seed to 0 for reproducibility
np.random.seed(10)

# Re-generate the random arrays to show the effect of setting the seed
random_array_seeded = np.random.rand(3, 3)
print(random_array_seeded)

random_int_array_seeded = np.random.randint(0, 10, (3, 3))
print(random_int_array_seeded)

random_choice_seeded = np.random.choice(array1, size=3)
print(random_choice_seeded)

[[0.76901216 0.88471869 0.87100498]
 [0.14647096 0.78918879 0.90922225]
 [0.83817055 0.71203119 0.30737942]]
[[4 0 9]
 [1 5 8]
 [7 7 5]]
[3 1 2]
[6 8 2 0 4]
[[0.77132064 0.02075195 0.63364823]
 [0.74880388 0.49850701 0.22479665]
 [0.19806286 0.76053071 0.16911084]]
[[8 6 4]
 [3 0 4]
 [6 8 1]]
[1 1 3]


## Statistical Functions

In [146]:
# Mean of all elements in array1
array_mean = np.mean(array1)
print(array_mean)

# Median of all elements in array1
array_median = np.median(array1)
print(array_median)

# Standard deviation of all elements in array1
array_std = np.std(array1)
print(array_std)

# Variance of all elements in array1
array_var = np.var(array1)
print(array_var)

# Correlation coefficient matrix between array1 and the first three elements of array2
correlation_matrix = np.corrcoef(array1, array2[:3])
print(correlation_matrix)

# Covariance matrix between array1 and the first three elements of array2
covariance_matrix = np.cov(array1, array2[:3])
print(covariance_matrix)


2.0
2.0
0.816496580927726
0.6666666666666666
[[ 1.         -0.65465367]
 [-0.65465367  1.        ]]
[[ 1.         -2.        ]
 [-2.          9.33333333]]


## Sorting and Searching

In [153]:
# Sorting array2
sorted_array = np.sort(array2)
print(sorted_array)

# Original Indices of the sorted elements in array2
argsorted_indices = np.argsort(array2)
print(argsorted_indices)

# Indices where the condition array1 > 1 is True
where_indices = np.where(array1 > 1)
print(where_indices)

# Indices of non-zero elements in array1
nonzero_indices = np.nonzero(array1)
print(nonzero_indices)

# Index of the maximum element in array1
max_index = np.argmax(array1)
print(max_index)

# Index of the minimum element in array1
min_index = np.argmin(array1)
print(min_index)

[0 2 4 6 8]
[3 2 4 0 1]
(array([1, 2], dtype=int64),)
(array([0, 1, 2], dtype=int64),)
2
0
